AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Cloudformation template for tag-checker

# More info: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md
Resources:
    TagCheckerFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: s3://tag-checker/src/tag-checker.zip
            Handler: tag-checker.lambda_handler
            Timeout: 300
            Runtime: python3.6
            Policies:
             - AWSLambdaBasicExecutionRole
             - AWSLambdaExecute
             - ResourceGroupsandTagEditorFullAccess
             - PowerUserAccess # Must be adjusted for production environment
            Environment:
                Variables:
                    S3_BUCKET: 'tag-checker'
            Events:
              TagReportepTimer:
                Type: Schedule
                Properties:
                  Schedule: rate(1 day)
Outputs:
    TagCheckerLambdaFunctionARN:
      Description: "ARN of tag-checker"
      Value: !GetAtt TagCheckerFunction.Arn
